### PR TITLE
Update Motion.php for RTSP

### PR DESCRIPTION
**Pull request by LeTak0**
Allow RTSP link in camera advanced configuration UI.

### CODE REVIEW

**Comment by lbr38** [comment]
Have you tested it with a RTSP camera? I do not have one so I can't test.

Be aware that you will never be able to get a live stream from the stream page with a RTSP camera as this is impossible for web browser to display such stream.

**Comment by lbr38** [comment]
Alright, I will merge it then. Thanks!

**Comment by lbr38** [comment]
You may have saw it but RTSP streaming in web browser is supported since `5.0.0` ;)

**Comment by LeTak0** [comment]
> You may have saw it but RTSP streaming in web browser is supported since `5.0.0` ;)

Thanks for the reminder. I activated it and it seems to work with my camera's.

**Pull request merged**
